# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '13.x'
    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!
    # Install Deps
    - name: Install Deps
      run: npm install
    # Build React app.
    - name: Create React - prod build
      run: CI=false npm run build
      
    - name: Zip the build folder
      run: zip -rq kf6-light-build.zip build/
      
    - name: Deploy to server
      uses: easingthemes/ssh-deploy@v2.0.7
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        ARGS: "-rltgoDzvO"
        SOURCE: "./kf6-light-build.zip"
        REMOTE_HOST: kf6-stage.ikit.org
        REMOTE_USER: ${{ secrets.IKIT_STAGE_USERNAME }}
        TARGET: /tmp/kf6-light-build.zip
    
    # Deploy - script
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: kf6-stage.ikit.org
        username: ${{ secrets.IKIT_STAGE_USERNAME }}
        key: ${{ secrets.KF6_LIGHT_IKIT_STAGE_PRIVATE_KEY }}
        port: 22
        script: | 
          whoami
          cd /tmp
          unzip -q kf6-light-build.zip
          
